import React, { Component } from "react";

export class Buttons extends Component {
  render() {
    return (
      <React.Fragment>
        <button
          type="button"
          className="button"
          value="7"
          onClick={this.props.handleClick}
        >
          7
        </button>
        <button
          type="button"
          className="button"
          value="8"
          onClick={this.props.handleClick}
        >
          8
        </button>
        <button
          type="button"
          className="button"
          value="9"
          onClick={this.props.handleClick}
        >
          9
        </button>
        <button
          className="button operator"
          value="/"
          onClick={this.props.handleClick}
        >
          /
        </button>
        <button
          type="button"
          className="button"
          value="4"
          onClick={this.props.handleClick}
        >
          4
        </button>
        <button
          type="button"
          className="button"
          value="5"
          onClick={this.props.handleClick}
        >
          5
        </button>
        <button
          type="button"
          className="button"
          value="6"
          onClick={this.props.handleClick}
        >
          6
        </button>
        <button
          type="button"
          className="button operator"
          value="*"
          onClick={this.props.handleClick}
        >
          x
        </button>
        <button
          type="button"
          className="button"
          value="1"
          onClick={this.props.handleClick}
        >
          1
        </button>
        <button
          type="button"
          className="button"
          value="2"
          onClick={this.props.handleClick}
        >
          2
        </button>
        <button
          type="button"
          className="button"
          value="3"
          onClick={this.props.handleClick}
        >
          3
        </button>
        <button
          type="button"
          className="button operator"
          value="+"
          onClick={this.props.handleClick}
        >
          +
        </button>
        <button
          type="button"
          className="button"
          value="."
          onClick={this.props.handleClick}
        >
          .
        </button>
        <button
          type="button"
          className="button"
          value="0"
          onClick={this.props.handleClick}
        >
          0
        </button>
        <button
          type="button"
          className="button"
          value="="
          onClick={this.props.handleEnter}
        >
          =
        </button>
        <button
          type="button"
          className="button operator"
          value="-"
          onClick={this.props.handleClick}
        >
          -
        </button>
      </React.Fragment>
    );
  }
}
